# Generated by Django 4.1.7 on 2023-04-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_authoredarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoredarticle',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authoredarticle',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authoredarticle',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authoredarticle',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
